/*
 * Red Alert Platform Layer
 * Auto-generated by cbindgen - DO NOT EDIT
 *
 * This header provides the C interface to the Rust platform library.
 */


#ifndef REDALERT_PLATFORM_H
#define REDALERT_PLATFORM_H

/* Generated with cbindgen:0.26.0 */

/* Warning: this file is auto-generated by cbindgen. Do not modify. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Platform version
 */
#define PLATFORM_VERSION 1

/**
 * Log level for Platform_Log
 */
typedef enum LogLevel {
  LOG_LEVEL_DEBUG = 0,
  LOG_LEVEL_INFO = 1,
  LOG_LEVEL_WARN = 2,
  LOG_LEVEL_ERROR = 3,
} LogLevel;

/**
 * Result type for platform operations (FFI-compatible)
 */
typedef enum PlatformResult {
  PLATFORM_RESULT_SUCCESS = 0,
  PLATFORM_RESULT_ALREADY_INITIALIZED = 1,
  PLATFORM_RESULT_NOT_INITIALIZED = 2,
  PLATFORM_RESULT_INIT_FAILED = 3,
} PlatformResult;

/**
 * Display mode configuration
 */
typedef struct DisplayMode {
  int32_t width;
  int32_t height;
  int32_t bits_per_pixel;
} DisplayMode;

/**
 * RGB palette entry (matches game format)
 */
typedef struct PaletteEntry {
  uint8_t r;
  uint8_t g;
  uint8_t b;
} PaletteEntry;

/**
 * Opaque surface handle for C
 */
typedef struct PlatformSurface {
  uint8_t _private[0];
} PlatformSurface;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Initialize the platform layer
 */
enum PlatformResult Platform_Init(void);

/**
 * Shutdown the platform layer
 */
enum PlatformResult Platform_Shutdown(void);

/**
 * Check if platform is initialized
 */
bool Platform_IsInitialized(void);

/**
 * Get platform version
 */
int32_t Platform_GetVersion(void);

/**
 * Get the last error message into a buffer
 * Returns number of bytes written, or -1 on error
 * Buffer will be null-terminated if there's space
 */
int32_t Platform_GetLastError(int8_t *buffer, int32_t buffer_size);

/**
 * Get error as static string pointer (valid until next error)
 * Returns null if no error
 */
const char *Platform_GetErrorString(void);

/**
 * Set an error message from C string
 */
void Platform_SetError(const char *msg);

/**
 * Clear the last error
 */
void Platform_ClearError(void);

/**
 * Log a message at the specified level
 */
void Platform_Log(enum LogLevel level, const char *msg);

/**
 * Log a formatted debug message
 */
void Platform_LogDebug(const char *msg);

/**
 * Log a formatted info message
 */
void Platform_LogInfo(const char *msg);

/**
 * Log a formatted warning message
 */
void Platform_LogWarn(const char *msg);

/**
 * Log a formatted error message
 */
void Platform_LogError(const char *msg);

/**
 * Initialize graphics subsystem
 */
int32_t Platform_Graphics_Init(void);

/**
 * Shutdown graphics subsystem
 */
void Platform_Graphics_Shutdown(void);

/**
 * Check if graphics is initialized
 */
bool Platform_Graphics_IsInitialized(void);

/**
 * Clear screen with color (for testing)
 */
void Platform_Graphics_Clear(uint8_t r, uint8_t g, uint8_t b);

/**
 * Present the frame
 */
void Platform_Graphics_Present(void);

/**
 * Get display mode
 */
void Platform_Graphics_GetMode(struct DisplayMode *mode);

/**
 * Get back buffer for direct pixel access
 * Returns pointer to 8-bit indexed pixel buffer
 */
int32_t Platform_Graphics_GetBackBuffer(uint8_t **pixels,
                                        int32_t *width,
                                        int32_t *height,
                                        int32_t *pitch);

/**
 * Clear back buffer with color index
 */
void Platform_Graphics_ClearBackBuffer(uint8_t color);

/**
 * Set palette entries
 */
void Platform_Graphics_SetPalette(const struct PaletteEntry *entries, int32_t start, int32_t count);

/**
 * Get palette entries
 */
void Platform_Graphics_GetPalette(struct PaletteEntry *entries, int32_t start, int32_t count);

/**
 * Set single palette entry
 */
void Platform_Graphics_SetPaletteEntry(uint8_t index, uint8_t r, uint8_t g, uint8_t b);

/**
 * Fade palette (0.0 = black, 1.0 = full)
 */
void Platform_Graphics_FadePalette(float factor);

/**
 * Restore palette from fade
 */
void Platform_Graphics_RestorePalette(void);

/**
 * Flip back buffer to screen (full render pipeline)
 */
int32_t Platform_Graphics_Flip(void);

/**
 * Wait for vertical sync (no-op, handled by SDL)
 */
void Platform_Graphics_WaitVSync(void);

/**
 * Draw test pattern to back buffer (for testing)
 */
void Platform_Graphics_DrawTestPattern(void);

/**
 * Get free video memory (returns large value for compatibility)
 */
uint32_t Platform_Graphics_GetFreeVideoMemory(void);

/**
 * Check if hardware accelerated
 */
bool Platform_Graphics_IsHardwareAccelerated(void);

/**
 * Poll events and return true if quit was requested (window close or Escape key)
 */
bool Platform_PollEvents(void);

/**
 * Get tick count in milliseconds since SDL init
 */
uint32_t Platform_GetTicks(void);

/**
 * Delay for specified milliseconds
 */
void Platform_Delay(uint32_t ms);

/**
 * Create a new surface
 */
struct PlatformSurface *Platform_Surface_Create(int32_t width, int32_t height, int32_t bpp);

/**
 * Destroy a surface
 */
void Platform_Surface_Destroy(struct PlatformSurface *surface);

/**
 * Get surface dimensions
 */
void Platform_Surface_GetSize(const struct PlatformSurface *surface,
                              int32_t *width,
                              int32_t *height);

/**
 * Lock surface for direct pixel access
 */
int32_t Platform_Surface_Lock(struct PlatformSurface *surface, void **pixels, int32_t *pitch);

/**
 * Unlock surface
 */
void Platform_Surface_Unlock(struct PlatformSurface *surface);

/**
 * Blit surface to another
 */
int32_t Platform_Surface_Blit(struct PlatformSurface *dest,
                              int32_t dx,
                              int32_t dy,
                              const struct PlatformSurface *src,
                              int32_t sx,
                              int32_t sy,
                              int32_t sw,
                              int32_t sh);

/**
 * Blit with transparency (skip color 0)
 */
int32_t Platform_Surface_BlitTransparent(struct PlatformSurface *dest,
                                         int32_t dx,
                                         int32_t dy,
                                         const struct PlatformSurface *src,
                                         int32_t sx,
                                         int32_t sy,
                                         int32_t sw,
                                         int32_t sh);

/**
 * Fill rectangle
 */
void Platform_Surface_Fill(struct PlatformSurface *surface,
                           int32_t x,
                           int32_t y,
                           int32_t w,
                           int32_t h,
                           uint8_t color);

/**
 * Clear entire surface
 */
void Platform_Surface_Clear(struct PlatformSurface *surface, uint8_t color);

#ifdef __cplusplus
} // extern "C"
#endif // __cplusplus

#endif /* REDALERT_PLATFORM_H */
